import api from './client';
export const login = (payload) => api.post('/api/auth/login', payload).then(r => r.data);
export const getSettings = () => api.get('/api/settings/vicidial').then(r => r.data);
export const putSettings = (payload) => api.put('/api/settings/vicidial', payload).then(r => r.data);
export const getAgentProfile = () => api.get('/api/agent/profile').then(r => r.data);
export const updateAgentProfilePass = (payload) => api.put('/api/agent/profile/agent-pass', payload).then(r => r.data);
export const connectVicidialPhone = (payload) => api.post('/api/agent/vicidial/phone/connect', payload).then(r => r.data);
export const disconnectVicidialPhone = () => api.post('/api/agent/vicidial/phone/disconnect').then(r => r.data);
export const getVicidialCampaigns = () => api.get('/api/agent/vicidial/campaigns').then(r => r.data);
export const connectVicidialCampaign = (payload) => api.post('/api/agent/vicidial/campaign/connect', payload).then(r => r.data);
export const getVicidialStatus = () => api.get('/api/agent/vicidial/status').then(r => r.data);
export const getCampaignDetails = (campaignId) => api.get(`/api/campaigns/${campaignId}`).then(r => r.data);
export const agentSessionHeartbeat = (payload) => api.post('/api/agent/session/heartbeat', payload).then(r => r.data);
export const agentSessionBrowserExit = (payload) => api.post('/api/agent/session/browser-exit', payload).then(r => r.data);
export const agentLogout = (payload) => api.post('/api/agent/logout', payload ?? {}).then(r => r.data);
export const getActiveLead = () => api.get('/api/agent/active-lead').then(r => r.data);
export const getContext = (p) => api.get('/api/agent/context', { params: p }).then(r => r.data);
export const dialNext = (payload) => api.post('/api/agent/vicidial/dial/next', payload).then(r => r.data);
export const manualDial = (payload) => api.post('/api/agent/vicidial/dial/manual', payload).then(r => r.data);
export const manual2Dispositions = (campaignId) => api.get('/api/agent/manual2/disposiciones', { params: { campaignId } }).then(r => r.data);
export const manual2Subtipificaciones = (campaignId, tipificacion) => api.get('/api/agent/manual2/subtipificaciones', { params: { campaignId, tipificacion } }).then(r => r.data);
export const manual2LookupContact = (phoneNumber) => api.get('/api/agent/manual2/contacto', { params: { phoneNumber } }).then(r => r.data);
export const manual2SaveForm = (payload) => api.post('/api/agent/manual2/formulario', payload).then(r => r.data);
export const manual2SaveGestion = (payload) => api.post('/api/agent/manual2/gestion', payload).then(r => r.data);
export const manual2History = (phoneNumber) => api.get('/api/agent/manual2/historial', { params: { phoneNumber } }).then(r => r.data);
export const hangupCall = (payload) => api.post('/api/agent/vicidial/call/hangup', payload ?? {}).then(r => r.data);
export const saveInteraction = (payload) => api.post('/api/agent/interactions', payload).then(r => r.data);
export const retryInteraction = (id) => api.post(`/api/agent/interactions/${id}/retry-vicidial`).then(r => r.data);
export const previewAction = (payload) => api.post('/api/agent/preview-action', payload).then(r => r.data);
export const pauseAction = (payload) => api.post('/api/agent/pause', payload).then(r => r.data);
export const importCsv = (file) => { const f = new FormData(); f.append('file', file); return api.post('/api/vicidial/leads/import', f).then(r => r.data); };
export const reportSummary = (p) => api.get('/api/reports/summary', { params: p }).then(r => r.data);
export const adminSummary = () => api.get('/api/admin/summary').then(r => r.data);
export const adminAgents = () => api.get('/api/admin/agents').then(r => r.data);
export const adminCampaigns = () => api.get('/api/admin/campaigns').then(r => r.data);
export const adminInteractions = (params) => api.get('/api/admin/interactions', { params }).then(r => r.data);
export const adminExportCsvUrl = (params) => {
    const query = new URLSearchParams(params).toString();
    return `${api.defaults.baseURL}/api/admin/interactions/export.csv?${query}`;
};
export const adminUsers = () => api.get('/api/admin/users').then(r => r.data);
export const adminCreateUser = (payload) => api.post('/api/admin/users', payload).then(r => r.data);
export const adminUpdateUser = (id, payload) => api.put(`/api/admin/users/${id}`, payload).then(r => r.data);
export const adminSettings = () => api.get('/api/admin/settings').then(r => r.data);
export const adminUpdateSettings = (payload) => api.put('/api/admin/settings', payload).then(r => r.data);
export const adminUpdateAgentPass = (id, payload) => api.put(`/api/admin/users/${id}/agent-pass`, payload).then(r => r.data);
export const adminManual2Report = (params) => api.get('/api/admin/manual2/reporte', { params }).then(r => r.data);
export const adminManual2ExportCsvUrl = (params) => {
    const query = new URLSearchParams(params).toString();
    return `${api.defaults.baseURL}/api/admin/manual2/reporte.csv?${query}`;
};
export const adminManual2History = (phoneNumber) => api.get('/api/admin/manual2/historial', { params: { phoneNumber } }).then(r => r.data);
export const adminManual2Subtipificaciones = (campana) => api.get('/api/admin/manual2/subtipificaciones', { params: { campana } }).then(r => r.data);
export const adminManual2SaveSubtipificacion = (payload) => api.post('/api/admin/manual2/subtipificaciones', payload).then(r => r.data);
export const adminManual2SetSubtipificacionActivo = (codigo, params) => api.patch(`/api/admin/manual2/subtipificaciones/${encodeURIComponent(codigo)}/activo`, null, { params }).then(r => r.data);
export const adminVicidialRealtimeSummary = () => api.get('/api/admin/vicidial/realtime/summary').then(r => r.data);
export const adminVicidialRealtimeAgents = (params) => api.get('/api/admin/vicidial/realtime/agents', { params }).then(r => r.data);
export const adminVicidialRealtimePauseCodes = () => api.get('/api/admin/vicidial/realtime/pause-codes').then(r => r.data);
export const adminVicidialRealtimeCampaigns = () => api.get('/api/admin/vicidial/realtime/campaigns').then(r => r.data);
export const adminVicidialLeadsImport = (payload) => api.post('/api/admin/vicidial/leads/import', payload).then(r => r.data);
