ALTER TABLE agent_vicidial_credentials
  ADD COLUMN IF NOT EXISTS session_name VARCHAR(120),
  ADD COLUMN IF NOT EXISTS server_ip VARCHAR(80),
  ADD COLUMN IF NOT EXISTS conf_exten VARCHAR(120),
  ADD COLUMN IF NOT EXISTS extension VARCHAR(160),
  ADD COLUMN IF NOT EXISTS protocol VARCHAR(40),
  ADD COLUMN IF NOT EXISTS agent_log_id BIGINT;
