import { Button, Container, MenuItem, Stack, TextField, Typography } from '@mui/material';
import { useMutation, useQuery } from '@tanstack/react-query'; import { getActiveLead, getContext, pauseAction, previewAction, retryInteraction, saveInteraction } from '../api/sdk'; import { useSearchParams } from 'react-router-dom'; import { useState } from 'react';
export default function AgentPage(){
 const [sp]=useSearchParams(); const agentUser=sp.get('agent_user')||''; const mode=sp.get('mode')||'predictive'; const [dispo,setDispo]=useState(''); const [notes,setNotes]=useState('');
 const active=useQuery({queryKey:['a',agentUser],queryFn:()=>getActiveLead(agentUser),enabled:!sp.get('lead_id')&&!!agentUser});
 const leadId=Number(sp.get('lead_id')||active.data?.leadId||0)||undefined;
 const context=useQuery({queryKey:['c',agentUser,leadId],queryFn:()=>getContext({agentUser,leadId,phone:sp.get('phone_number')||undefined,campaign:sp.get('campaign')||undefined,mode}),enabled:!!agentUser});
 const save=useMutation({mutationFn:saveInteraction}); const retry=useMutation({mutationFn:retryInteraction});
 const c:any=context.data;
 return <Container sx={{py:3}}><Stack gap={2}><Typography variant='h5'>Atención {mode}</Typography><pre>{JSON.stringify(c?.lead,null,2)}</pre><pre>{JSON.stringify(c?.customer,null,2)}</pre><TextField select label='Disposición' value={dispo} onChange={e=>setDispo(e.target.value)}>{(c?.dispoOptions||[]).map((d:string)=><MenuItem key={d} value={d}>{d}</MenuItem>)}</TextField><TextField label='Notas' multiline minRows={3} value={notes} onChange={e=>setNotes(e.target.value)}/><Button variant='contained' onClick={()=>save.mutate({agentUser,mode,leadId,phoneNumber:c?.lead?.phoneNumber||'',campaign:c?.lead?.campaign||'',dni:c?.lead?.dni||'',dispo,notes,extra:{}})}>Guardar gestión</Button>{save.data?.syncStatus!=='SYNCED'&&save.data?.id&&<Button onClick={()=>retry.mutate(save.data.id)}>Reintentar</Button>}{mode==='preview'&&<Stack direction='row' gap={1}><Button onClick={()=>previewAction({agentUser,leadId,campaign:c?.lead?.campaign,action:'DIALONLY'})}>DIALONLY</Button><Button onClick={()=>previewAction({agentUser,leadId,campaign:c?.lead?.campaign,action:'SKIP'})}>SKIP</Button><Button onClick={()=>previewAction({agentUser,leadId,campaign:c?.lead?.campaign,action:'FINISH'})}>FINISH</Button></Stack>}<Stack direction='row' gap={1}><Button onClick={()=>pauseAction({agentUser,action:'PAUSE'})}>Pause</Button><Button onClick={()=>pauseAction({agentUser,action:'RESUME'})}>Resume</Button></Stack></Stack></Container>
}
